### ISSUE TITLE
Layout is disturbing the usual clean README look

### ISSUE THREAD

**Issue by buep** [Praqma/ghreport#23]
![image](https://cloud.githubusercontent.com/assets/1579826/22834681/3e199dae-efb6-11e6-9e58-ea6af46daf5f.png)

The frontmatter is disturbing the usual README layout I think. The first section header is pushed to far down and if we add more information it will clutter the most important information for the users - the README.

Further I don't think these informations is very interesting for outsider, they are more for Praqma use, so maybe it should be the first thing users or contributors see?
Maybe these information should just be mentioned in the contribution files instead or in a specific file for this purpose.

**Comment by lakruzz** [comment]
This is how we will implement it until we have another better option for adding custom attributes to a repo.

The frontmatter is natively supported by jekyll and even rendered correctly on GitHub. Hard to come up with an equally well supported protocol.
